<?php

/**
 * Social Share Links
 */
function codebean_data_source_social_share_links() {
    return array(
        array( 'value' => 'delicious', 'label' => 'Delicious' ),
		array( 'value' => 'facebook', 'label' => 'Facebook' ),
		array( 'value' => 'googlePlus', 'label' => 'Google+' ),
		array( 'value' => 'linkedin', 'label' => 'LinkedIn' ),
		array( 'value' => 'pinterest', 'label' => 'Pinterest' ),
		array( 'value' => 'stumbleupon', 'label' => 'StumbleUpon' ),
		array( 'value' => 'twitter', 'label' => 'Twitter' ),
    );
}

/**
 * Color Scheme
 */
function codebean_data_source_color_scheme() {
    return array(
        array(
            'label' => esc_html__( 'light background / dark text color', 'onliestwp' ),
            'value' => 'light',
        ),
        array(
            'label' => esc_html__( 'dark background / light text color', 'onliestwp' ),
            'value' => 'dark',
        ),
    );
}

/**
 * Animate CSS
 */
function codebean_get_animate_css() {
    return array(
        esc_html__( 'animate.css: bounce', 'onliestwp' ) => 'animate_css animated bounce',
		esc_html__( 'animate.css: flash', 'onliestwp' ) => 'animate_css animated flash',
		esc_html__( 'animate.css: pulse', 'onliestwp' ) => 'animate_css animated pulse',
		esc_html__( 'animate.css: rubberBand', 'onliestwp' ) => 'animate_css animated rubberBand',
		esc_html__( 'animate.css: shake', 'onliestwp' ) => 'animate_css animated shake',
		esc_html__( 'animate.css: swing', 'onliestwp' ) => 'animate_css animated swing',
		esc_html__( 'animate.css: tada', 'onliestwp' ) => 'animate_css animated tada',
		esc_html__( 'animate.css: wobble', 'onliestwp' ) => 'animate_css animated wobble',
		esc_html__( 'animate.css: bounceIn', 'onliestwp' ) => 'animate_css animated bounceIn',
		esc_html__( 'animate.css: bounceInDown', 'onliestwp' ) => 'animate_css animated bounceInDown',
		esc_html__( 'animate.css: bounceInLeft', 'onliestwp' ) => 'animate_css animated bounceInLeft',
		esc_html__( 'animate.css: bounceInRight', 'onliestwp' ) => 'animate_css animated bounceInRight',
		esc_html__( 'animate.css: bounceInUp', 'onliestwp' ) => 'animate_css animated bounceInUp',
		esc_html__( 'animate.css: bounceOut', 'onliestwp' ) => 'animate_css animated bounceOut',
		esc_html__( 'animate.css: bounceOutDown', 'onliestwp' ) => 'animate_css animated bounceOutDown',
		esc_html__( 'animate.css: bounceOutLeft', 'onliestwp' ) => 'animate_css animated bounceOutLeft',
		esc_html__( 'animate.css: bounceOutRight', 'onliestwp' ) => 'animate_css animated bounceOutRight',
		esc_html__( 'animate.css: bounceOutUp', 'onliestwp' ) => 'animate_css animated bounceOutUp',
		esc_html__( 'animate.css: fadeIn', 'onliestwp' ) => 'animate_css animated fadeIn',
		esc_html__( 'animate.css: fadeInDown', 'onliestwp' ) => 'animate_css animated fadeInDown',
		esc_html__( 'animate.css: fadeInDownBig', 'onliestwp' ) => 'animate_css animated fadeInDownBig',
		esc_html__( 'animate.css: fadeInLeft', 'onliestwp' ) => 'animate_css animated fadeInLeft',
		esc_html__( 'animate.css: fadeInLeftBig', 'onliestwp' ) => 'animate_css animated fadeInLeftBig',
		esc_html__( 'animate.css: fadeInRight', 'onliestwp' ) => 'animate_css animated fadeInRight',
		esc_html__( 'animate.css: fadeInRightBig', 'onliestwp' ) => 'animate_css animated fadeInRightBig',
		esc_html__( 'animate.css: fadeInUp', 'onliestwp' ) => 'animate_css animated fadeInUp',
		esc_html__( 'animate.css: fadeInUpBig', 'onliestwp' ) => 'animate_css animated fadeInUpBig',
		esc_html__( 'animate.css: fadeOut', 'onliestwp' ) => 'animate_css animated fadeOut',
		esc_html__( 'animate.css: fadeOutDown', 'onliestwp' ) => 'animate_css animated fadeOutDown',
		esc_html__( 'animate.css: fadeOutDownBig', 'onliestwp' ) => 'animate_css animated fadeOutDownBig',
		esc_html__( 'animate.css: fadeOutLeft', 'onliestwp' ) => 'animate_css animated fadeOutLeft',
		esc_html__( 'animate.css: fadeOutLeftBig', 'onliestwp' ) => 'animate_css animated fadeOutLeftBig',
		esc_html__( 'animate.css: fadeOutRight', 'onliestwp' ) => 'animate_css animated fadeOutRight',
		esc_html__( 'animate.css: fadeOutRightBig', 'onliestwp' ) => 'animate_css animated fadeOutRightBig',
		esc_html__( 'animate.css: fadeOutUp', 'onliestwp' ) => 'animate_css animated fadeOutUp',
		esc_html__( 'animate.css: fadeOutUpBig', 'onliestwp' ) => 'animate_css animated fadeOutUpBig',
		esc_html__( 'animate.css: flip', 'onliestwp' ) => 'animate_css animated flip',
		esc_html__( 'animate.css: flipInX', 'onliestwp' ) => 'animate_css animated flipInX',
		esc_html__( 'animate.css: flipInY', 'onliestwp' ) => 'animate_css animated flipInY',
		esc_html__( 'animate.css: flipOutX', 'onliestwp' ) => 'animate_css animated flipOutX',
		esc_html__( 'animate.css: flipOutY', 'onliestwp' ) => 'animate_css animated flipOutY',
		esc_html__( 'animate.css: lightSpeedIn', 'onliestwp' ) => 'animate_css animated lightSpeedIn',
		esc_html__( 'animate.css: lightSpeedOut', 'onliestwp' ) => 'animate_css animated lightSpeedOut',
		esc_html__( 'animate.css: rotateIn', 'onliestwp' ) => 'animate_css animated rotateIn',
		esc_html__( 'animate.css: rotateInDownLeft', 'onliestwp' ) => 'animate_css animated rotateInDownLeft',
		esc_html__( 'animate.css: rotateInDownRight', 'onliestwp' ) => 'animate_css animated rotateInDownRight',
		esc_html__( 'animate.css: rotateInUpLeft', 'onliestwp' ) => 'animate_css animated rotateInUpLeft',
		esc_html__( 'animate.css: rotateInUpRight', 'onliestwp' ) => 'animate_css animated rotateInUpRight',
		esc_html__( 'animate.css: rotateOut', 'onliestwp' ) => 'animate_css animated rotateOut',
		esc_html__( 'animate.css: rotateOutDownLeft', 'onliestwp' ) => 'animate_css animated rotateOutDownLeft',
		esc_html__( 'animate.css: rotateOutDownRight', 'onliestwp' ) => 'animate_css animated rotateOutDownRight',
		esc_html__( 'animate.css: rotateOutUpLeft', 'onliestwp' ) => 'animate_css animated rotateOutUpLeft',
		esc_html__( 'animate.css: rotateOutUpRight', 'onliestwp' ) => 'animate_css animated rotateOutUpRight',
		esc_html__( 'animate.css: slideInDown', 'onliestwp' ) => 'animate_css animated slideInDown',
		esc_html__( 'animate.css: slideInLeft', 'onliestwp' ) => 'animate_css animated slideInLeft',
		esc_html__( 'animate.css: slideInRight', 'onliestwp' ) => 'animate_css animated slideInRight',
		esc_html__( 'animate.css: slideOutLeft', 'onliestwp' ) => 'animate_css animated slideOutLeft',
		esc_html__( 'animate.css: slideOutRight', 'onliestwp' ) => 'animate_css animated slideOutRight',
		esc_html__( 'animate.css: slideOutUp', 'onliestwp' ) => 'animate_css animated slideOutUp',
		esc_html__( 'animate.css: hinge', 'onliestwp' ) => 'animate_css animated hinge',
		esc_html__( 'animate.css: rollIn', 'onliestwp' ) => 'animate_css animated rollIn',
		esc_html__( 'animate.css: rollOut', 'onliestwp' ) => 'animate_css animated rollOut',
    );
}

function codebean_data_source_animate_css() {
    return array(
		array(
			'value' => 'bounce',
			'label' => 'bounce',
		),
		array(
			'value' => 'flash',
			'label' => 'flash',
		),
		array(
			'value' => 'pulse',
			'label' => 'pulse',
		),
		array(
			'value' => 'rubberBand',
			'label' => 'rubberBand',
		),
		array(
			'value' => 'shake',
			'label' => 'shake',
		),
		array(
			'value' => 'swing',
			'label' => 'swing',
		),
		array(
			'value' => 'tada',
			'label' => 'tada',
		),
		array(
			'value' => 'wobble',
			'label' => 'wobble',
		),
		array(
			'value' => 'bounceIn',
			'label' => 'bounceIn',
		),
		array(
			'value' => 'bounceInDown',
			'label' => 'bounceInDown',
		),
		array(
			'value' => 'bounceInLeft',
			'label' => 'bounceInLeft',
		),
		array(
			'value' => 'bounceInRight',
			'label' => 'bounceInRight',
		),
		array(
			'value' => 'bounceInUp',
			'label' => 'bounceInUp',
		),
		array(
			'value' => 'bounceOut',
			'label' => 'bounceOut',
		),
		array(
			'value' => 'bounceOutDown',
			'label' => 'bounceOutDown',
		),
		array(
			'value' => 'bounceOutLeft',
			'label' => 'bounceOutLeft',
		),
		array(
			'value' => 'bounceOutRight',
			'label' => 'bounceOutRight',
		),
		array(
			'value' => 'bounceOutUp',
			'label' => 'bounceOutUp',
		),
		array(
			'value' => 'fadeIn',
			'label' => 'fadeIn',
		),
		array(
			'value' => 'fadeInDown',
			'label' => 'fadeInDown',
		),
		array(
			'value' => 'fadeInDownBig',
			'label' => 'fadeInDownBig',
		),
		array(
			'value' => 'fadeInLeft',
			'label' => 'fadeInLeft',
		),
		array(
			'value' => 'fadeInLeftBig',
			'label' => 'fadeInLeftBig',
		),
		array(
			'value' => 'fadeInRight',
			'label' => 'fadeInRight',
		),
		array(
			'value' => 'fadeInRightBig',
			'label' => 'fadeInRightBig',
		),
		array(
			'value' => 'fadeInUp',
			'label' => 'fadeInUp',
		),
		array(
			'value' => 'fadeInUpBig',
			'label' => 'fadeInUpBig',
		),
		array(
			'value' => 'fadeOut',
			'label' => 'fadeOut',
		),
		array(
			'value' => 'fadeOutDown',
			'label' => 'fadeOutDown',
		),
		array(
			'value' => 'fadeOutDownBig',
			'label' => 'fadeOutDownBig',
		),
		array(
			'value' => 'fadeOutLeft',
			'label' => 'fadeOutLeft',
		),
		array(
			'value' => 'fadeOutLeftBig',
			'label' => 'fadeOutLeftBig',
		),
		array(
			'value' => 'fadeOutRight',
			'label' => 'fadeOutRight',
		),
		array(
			'value' => 'fadeOutRightBig',
			'label' => 'fadeOutRightBig',
		),
		array(
			'value' => 'fadeOutUp',
			'label' => 'fadeOutUp',
		),
		array(
			'value' => 'fadeOutUpBig',
			'label' => 'fadeOutUpBig',
		),
		array(
			'value' => 'flip',
			'label' => 'flip',
		),
		array(
			'value' => 'flipInX',
			'label' => 'flipInX',
		),
		array(
			'value' => 'flipInY',
			'label' => 'flipInY',
		),
		array(
			'value' => 'flipOutX',
			'label' => 'flipOutX',
		),
		array(
			'value' => 'flipOutY',
			'label' => 'flipOutY',
		),
		array(
			'value' => 'lightSpeedIn',
			'label' => 'lightSpeedIn',
		),
		array(
			'value' => 'lightSpeedOut',
			'label' => 'lightSpeedOut',
		),
		array(
			'value' => 'rotateIn',
			'label' => 'rotateIn',
		),
		array(
			'value' => 'rotateInDownLeft',
			'label' => 'rotateInDownLeft',
		),
		array(
			'value' => 'rotateInDownRight',
			'label' => 'rotateInDownRight',
		),
		array(
			'value' => 'rotateInUpLeft',
			'label' => 'rotateInUpLeft',
		),
		array(
			'value' => 'rotateInUpRight',
			'label' => 'rotateInUpRight',
		),
		array(
			'value' => 'rotateOut',
			'label' => 'rotateOut',
		),
		array(
			'value' => 'rotateOutDownLeft',
			'label' => 'rotateOutDownLeft',
		),
		array(
			'value' => 'rotateOutDownRight',
			'label' => 'rotateOutDownRight',
		),
		array(
			'value' => 'rotateOutUpLeft',
			'label' => 'rotateOutUpLeft',
		),
		array(
			'value' => 'rotateOutUpRight',
			'label' => 'rotateOutUpRight',
		),
		array(
			'value' => 'slideInDown',
			'label' => 'slideInDown',
		),
		array(
			'value' => 'slideInLeft',
			'label' => 'slideInLeft',
		),
		array(
			'value' => 'slideInRight',
			'label' => 'slideInRight',
		),
		array(
			'value' => 'slideOutLeft',
			'label' => 'slideOutLeft',
		),
		array(
			'value' => 'slideOutRight',
			'label' => 'slideOutRight',
		),
		array(
			'value' => 'slideOutUp',
			'label' => 'slideOutUp',
		),
		array(
			'value' => 'hinge',
			'label' => 'hinge',
		),
		array(
			'value' => 'rollIn',
			'label' => 'rollIn',
		),
		array(
			'value' => 'rollOut',
			'label' => 'rollOut',
		),
	);
}

/**
 * Icons
 */
function codebean_get_icons() {
    return array_merge(
		array(
			'Themify: arrow-up' => 'ti-arrow-up',
			'Themify: arrow-right' => 'ti-arrow-right',
			'Themify: arrow-left' => 'ti-arrow-left',
			'Themify: arrow-down' => 'ti-arrow-down',
			'Themify: arrows-vertical' => 'ti-arrows-vertical',
			'Themify: arrows-horizontal' => 'ti-arrows-horizontal',
			'Themify: angle-up' => 'ti-angle-up',
			'Themify: angle-right' => 'ti-angle-right',
			'Themify: angle-left' => 'ti-angle-left',
			'Themify: angle-down' => 'ti-angle-down',
			'Themify: angle-double-up' => 'ti-angle-double-up',
			'Themify: angle-double-right' => 'ti-angle-double-right',
			'Themify: angle-double-left' => 'ti-angle-double-left',
			'Themify: angle-double-down' => 'ti-angle-double-down',
			'Themify: move' => 'ti-move',
			'Themify: fullscreen' => 'ti-fullscreen',
			'Themify: arrow-top-right' => 'ti-arrow-top-right',
			'Themify: arrow-top-left' => 'ti-arrow-top-left',
			'Themify: arrow-circle-up' => 'ti-arrow-circle-up',
			'Themify: arrow-circle-right' => 'ti-arrow-circle-right',
			'Themify: arrow-circle-left' => 'ti-arrow-circle-left',
			'Themify: arrow-circle-down' => 'ti-arrow-circle-down',
			'Themify: arrows-corner' => 'ti-arrows-corner',
			'Themify: split-v' => 'ti-split-v',
			'Themify: split-v' => 'ti-split-v-alt',
			'Themify: split-h' => 'ti-split-h',
			'Themify: hand-point-up' => 'ti-hand-point-up',
			'Themify: hand-point-right' => 'ti-hand-point-right',
			'Themify: hand-point-left' => 'ti-hand-point-left',
			'Themify: hand-point-down' => 'ti-hand-point-down',
			'Themify: back-right' => 'ti-back-right',
			'Themify: back-left' => 'ti-back-left',
			'Themify: exchange-vertical' => 'ti-exchange-vertical',
			'Themify: wand' => 'ti-wand',
			'Themify: save' => 'ti-save',
			'Themify: save' => 'ti-save',
			'Themify: save-alt' => 'ti-save-alt',
			'Themify: direction' => 'ti-direction',
			'Themify: direction-alt' => 'ti-direction-alt',
			'Themify: user' => 'ti-user',
			'Themify: link' => 'ti-link',
			'Themify: unlink' => 'ti-unlink',
			'Themify: trash' => 'ti-trash',
			'Themify: target' => 'ti-target',
			'Themify: tag' => 'ti-tag',
			'Themify: desktop' => 'ti-desktop',
			'Themify: tablet' => 'ti-tablet',
			'Themify: mobile' => 'ti-mobile',
			'Themify: email' => 'ti-email',
			'Themify: star' => 'ti-star',
			'Themify: spray' => 'ti-spray',
			'Themify: signal' => 'ti-signal',
			'Themify: shopping-cart' => 'ti-shopping-cart',
			'Themify: shopping-cart-full' => 'ti-shopping-cart-full',
			'Themify: settings' => 'ti-settings',
			'Themify: ti-search' => 'ti-ti-search',
			'Themify: zoom-in' => 'ti-zoom-in',
			'Themify: zoom-out' => 'ti-zoom-out',
			'Themify: cut' => 'ti-cut',
			'Themify: ruler' => 'ti-ruler',
			'Themify: ruler-alt-2' => 'ti-ruler-alt-2',
			'Themify: ruler-pencil' => 'ti-ruler-pencil',
			'Themify: ruler-alt' => 'ti-ruler-alt',
			'Themify: bookmark' => 'ti-bookmark',
			'Themify: bookmark-alt' => 'ti-bookmark-alt',
			'Themify: reload' => 'ti-reload',
			'Themify: plus' => 'ti-plus',
			'Themify: minus' => 'ti-minus',
			'Themify: close' => 'ti-close',
			'Themify: pin' => 'ti-pin',
			'Themify: pencil' => 'ti-pencil',
			'Themify: pencil-alt' => 'ti-pencil-alt',
			'Themify: paint-roller' => 'ti-paint-roller',
			'Themify: paint-bucket' => 'ti-paint-bucket',
			'Themify: na' => 'ti-na',
			'Themify: medall' => 'ti-medall',
			'Themify: medall-alt' => 'ti-medall-alt',
			'Themify: marker' => 'ti-marker',
			'Themify: marker-alt' => 'ti-marker-alt',
			'Themify: lock' => 'ti-lock',
			'Themify: unlock' => 'ti-unlock',
			'Themify: location-arrow' => 'ti-location-arrow',
			'Themify: layout' => 'ti-layout',
			'Themify: layers' => 'ti-layers',
			'Themify: layers-alt' => 'ti-layers-alt',
			'Themify: key' => 'ti-key',
			'Themify: image' => 'ti-image',
			'Themify: heart' => 'ti-heart',
			'Themify: heart-broken' => 'ti-heart-broken',
			'Themify: hand-stop' => 'ti-hand-stop',
			'Themify: open' => 'ti-open',
			'Themify: drag' => 'ti-drag',
			'Themify: flag' => 'ti-flag',
			'Themify: flag-alt' => 'ti-flag-alt',
			'Themify: flag-alt-2' => 'ti-flag-alt-2',
			'Themify: eye' => 'ti-eye',
			'Themify: import' => 'ti-import',
			'Themify: export' => 'ti-export',
			'Themify: cup' => 'ti-cup',
			'Themify: crown' => 'ti-crown',
			'Themify: comments' => 'ti-comments',
			'Themify: comment' => 'ti-comment',
			'Themify: comment-alt' => 'ti-comment-alt',
			'Themify: thoughts' => 'ti-thoughts',
			'Themify: clip' => 'ti-clip',
			'Themify: check' => 'ti-check',
			'Themify: check-box' => 'ti-check-box',
			'Themify: camera' => 'ti-camera',
			'Themify: announcement' => 'ti-announcement',
			'Themify: brush' => 'ti-brush',
			'Themify: brush-alt' => 'ti-brush-alt',
			'Themify: palette' => 'ti-palette',
			'Themify: briefcase' => 'ti-briefcase',
			'Themify: bolt' => 'ti-bolt',
			'Themify: bolt-alt' => 'ti-bolt-alt',
			'Themify: blackboard' => 'ti-blackboard',
			'Themify: bag' => 'ti-bag',
			'Themify: world' => 'ti-world',
			'Themify: wheelchair' => 'ti-wheelchair',
			'Themify: car' => 'ti-car',
			'Themify: truck' => 'ti-truck',
			'Themify: timer' => 'ti-timer',
			'Themify: ticket' => 'ti-ticket',
			'Themify: thumb-up' => 'ti-thumb-up',
			'Themify: thumb-down' => 'ti-thumb-down',
			'Themify: stats-up' => 'ti-stats-up',
			'Themify: stats-down' => 'ti-stats-down',
			'Themify: shine' => 'ti-shine',
			'Themify: shift-right' => 'ti-shift-right',
			'Themify: shift-left' => 'ti-shift-left',
			'Themify: shift-right-alt' => 'ti-shift-right-alt',
			'Themify: shift-left-alt' => 'ti-shift-left-alt',
			'Themify: shield' => 'ti-shield',
			'Themify: notepad' => 'ti-notepad',
			'Themify: server' => 'ti-server',
			'Themify: pulse' => 'ti-pulse',
			'Themify: printer' => 'ti-printer',
			'Themify: power-off' => 'ti-power-off',
			'Themify: plug' => 'ti-plug',
			'Themify: pie-chart' => 'ti-pie-chart',
			'Themify: panel' => 'ti-panel',
			'Themify: package' => 'ti-package',
			'Themify: music' => 'ti-music',
			'Themify: music-alt' => 'ti-music-alt',
			'Themify: mouse' => 'ti-mouse',
			'Themify: mouse-alt' => 'ti-mouse-alt',
			'Themify: money' => 'ti-money',
			'Themify: microphone' => 'ti-microphone',
			'Themify: menu' => 'ti-menu',
			'Themify: menu-alt' => 'ti-menu-alt',
			'Themify: map' => 'ti-map',
			'Themify: map-alt' => 'ti-map-alt',
			'Themify: location-pin' => 'ti-location-pin',
			'Themify: light-bulb' => 'ti-light-bulb',
			'Themify: info' => 'ti-info',
			'Themify: infinite' => 'ti-infinite',
			'Themify: id-badge' => 'ti-id-badge',
			'Themify: hummer' => 'ti-hummer',
			'Themify: home' => 'ti-home',
			'Themify: help' => 'ti-help',
			'Themify: headphone' => 'ti-headphone',
			'Themify: harddrives' => 'ti-harddrives',
			'Themify: harddrive' => 'ti-harddrive',
			'Themify: gift' => 'ti-gift',
			'Themify: game' => 'ti-game',
			'Themify: filter' => 'ti-filter',
			'Themify: files' => 'ti-files',
			'Themify: file' => 'ti-file',
			'Themify: zip' => 'ti-zip',
			'Themify: folder' => 'ti-folder',
			'Themify: envelope' => 'ti-envelope',
			'Themify: dashboard' => 'ti-dashboard',
			'Themify: cloud' => 'ti-cloud',
			'Themify: cloud-up' => 'ti-cloud-up',
			'Themify: cloud-down' => 'ti-cloud-down',
			'Themify: clipboard' => 'ti-clipboard',
			'Themify: calendar' => 'ti-calendar',
			'Themify: book' => 'ti-book',
			'Themify: bell' => 'ti-bell',
			'Themify: backetball' => 'ti-backetball',
			'Themify: bar-chart' => 'ti-bar-chart',
			'Themify: bar-chart-alt' => 'ti-bar-chart-alt',
			'Themify: archive' => 'ti-archive',
			'Themify: anchor' => 'ti-anchor',
			'Themify: alert' => 'ti-alert',
			'Themify: alarm-clock' => 'ti-alarm-clock',
			'Themify: agenda' => 'ti-agenda',
			'Themify: write' => 'ti-write',
			'Themify: wallet' => 'ti-wallet',
			'Themify: video-clapper' => 'ti-video-clapper',
			'Themify: video-camera' => 'ti-video-camera',
			'Themify: vector' => 'ti-vector',
			'Themify: support' => 'ti-support',
			'Themify: stamp' => 'ti-stamp',
			'Themify: slice' => 'ti-slice',
			'Themify: shortcode' => 'ti-shortcode',
			'Themify: receipt' => 'ti-receipt',
			'Themify: pin2' => 'ti-pin2',
			'Themify: pin-alt' => 'ti-pin-alt',
			'Themify: pencil-alt2' => 'ti-pencil-alt2',
			'Themify: eraser' => 'ti-eraser',
			'Themify: more' => 'ti-more',
			'Themify: more-alt' => 'ti-more-alt',
			'Themify: microphone-alt' => 'ti-microphone-alt',
			'Themify: magnet' => 'ti-magnet',
			'Themify: line-double' => 'ti-line-double',
			'Themify: line-dotted' => 'ti-line-dotted',
			'Themify: line-dashed' => 'ti-line-dashed',
			'Themify: ink-pen' => 'ti-ink-pen',
			'Themify: info-alt' => 'ti-info-alt',
			'Themify: help-alt' => 'ti-help-alt',
			'Themify: headphone-alt' => 'ti-headphone-alt',
			'Themify: gallery' => 'ti-gallery',
			'Themify: face-smile' => 'ti-face-smile',
			'Themify: face-sad' => 'ti-face-sad',
			'Themify: credit-card' => 'ti-credit-card',
			'Themify: comments-smiley' => 'ti-comments-smiley',
			'Themify: time' => 'ti-time',
			'Themify: share' => 'ti-share',
			'Themify: share-alt' => 'ti-share-alt',
			'Themify: rocket' => 'ti-rocket',
			'Themify: new-window' => 'ti-new-window',
			'Themify: rss' => 'ti-rss',
			'Themify: rss-alt' => 'ti-rss-alt',
			'Themify: control-stop' => 'ti-control-stop',
			'Themify: control-shuffle' => 'ti-control-shuffle',
			'Themify: control-play' => 'ti-control-play',
			'Themify: control-pause' => 'ti-control-pause',
			'Themify: control-forward' => 'ti-control-forward',
			'Themify: control-backward' => 'ti-control-backward',
			'Themify: volume' => 'ti-volume',
			'Themify: control-skip-forward' => 'ti-control-skip-forward',
			'Themify: control-skip-backward' => 'ti-control-skip-backward',
			'Themify: control-record' => 'ti-control-record',
			'Themify: control-eject' => 'ti-control-eject',
			'Themify: paragraph' => 'ti-paragraph',
			'Themify: uppercase' => 'ti-uppercase',
			'Themify: underline' => 'ti-underline',
			'Themify: text' => 'ti-text',
			'Themify: italic' => 'ti-italic',
			'Themify: smallcap' => 'ti-smallcap',
			'Themify: list' => 'ti-list',
			'Themify: list-ol' => 'ti-list-ol',
			'Themify: align-right' => 'ti-align-right',
			'Themify: align-left' => 'ti-align-left',
			'Themify: align-justify' => 'ti-align-justify',
			'Themify: align-center' => 'ti-align-center',
			'Themify: quote-right' => 'ti-quote-right',
			'Themify: quote-left' => 'ti-quote-left',
			'Themify: layout-width-full' => 'ti-layout-width-full',
			'Themify: layout-width-default' => 'ti-layout-width-default',
			'Themify: layout-width-default-alt' => 'ti-layout-width-default-alt',
			'Themify: layout-tab' => 'ti-layout-tab',
			'Themify: layout-tab-window' => 'ti-layout-tab-window',
			'Themify: layout-tab-v' => 'ti-layout-tab-v',
			'Themify: layout-tab-min' => 'ti-layout-tab-min',
			'Themify: layout-slider' => 'ti-layout-slider',
			'Themify: layout-slider-alt' => 'ti-layout-slider-alt',
			'Themify: layout-sidebar-right' => 'ti-layout-sidebar-right',
			'Themify: layout-sidebar-none' => 'ti-layout-sidebar-none',
			'Themify: layout-sidebar-left' => 'ti-layout-sidebar-left',
			'Themify: layout-placeholder' => 'ti-layout-placeholder',
			'Themify: layout-menu' => 'ti-layout-menu',
			'Themify: layout-menu-v' => 'ti-layout-menu-v',
			'Themify: layout-menu-separated' => 'ti-layout-menu-separated',
			'Themify: layout-menu-full' => 'ti-layout-menu-full',
			'Themify: layout-media-right' => 'ti-layout-media-right',
			'Themify: layout-media-right-alt' => 'ti-layout-media-right-alt',
			'Themify: layout-media-overlay' => 'ti-layout-media-overlay',
			'Themify: layout-media-overlay-alt' => 'ti-layout-media-overlay-alt',
			'Themify: layout-media-overlay-alt-2' => 'ti-layout-media-overlay-alt-2',
			'Themify: layout-media-left' => 'ti-layout-media-left',
			'Themify: layout-media-left-alt' => 'ti-layout-media-left-alt',
			'Themify: layout-media-center' => 'ti-layout-media-center',
			'Themify: layout-media-center-alt' => 'ti-layout-media-center-alt',
			'Themify: layout-list-thumb' => 'ti-layout-list-thumb',
			'Themify: layout-list-thumb-alt' => 'ti-layout-list-thumb-alt',
			'Themify: layout-list-post' => 'ti-layout-list-post',
			'Themify: layout-list-large-image' => 'ti-layout-list-large-image',
			'Themify: layout-line-solid' => 'ti-layout-line-solid',
			'Themify: layout-grid4' => 'ti-layout-grid4',
			'Themify: layout-grid3' => 'ti-layout-grid3',
			'Themify: layout-grid2' => 'ti-layout-grid2',
			'Themify: layout-grid2-thumb' => 'ti-layout-grid2-thumb',
			'Themify: layout-cta-right' => 'ti-layout-cta-right',
			'Themify: layout-cta-left' => 'ti-layout-cta-left',
			'Themify: layout-cta-center' => 'ti-layout-cta-center',
			'Themify: layout-cta-btn-right' => 'ti-layout-cta-btn-right',
			'Themify: layout-cta-btn-left' => 'ti-layout-cta-btn-left',
			'Themify: layout-column4' => 'ti-layout-column4',
			'Themify: layout-column3' => 'ti-layout-column3',
			'Themify: layout-column2' => 'ti-layout-column2',
			'Themify: layout-accordion-separated' => 'ti-layout-accordion-separated',
			'Themify: layout-accordion-merged' => 'ti-layout-accordion-merged',
			'Themify: layout-accordion-list' => 'ti-layout-accordion-list',
			'Themify: widgetized' => 'ti-widgetized',
			'Themify: widget' => 'ti-widget',
			'Themify: widget-alt' => 'ti-widget-alt',
			'Themify: view-list' => 'ti-view-list',
			'Themify: view-list-alt' => 'ti-view-list-alt',
			'Themify: view-grid' => 'ti-view-grid',
			'Themify: upload' => 'ti-upload',
			'Themify: download' => 'ti-download',
			'Themify: loop' => 'ti-loop',
			'Themify: layout-sidebar-2' => 'ti-layout-sidebar-2',
			'Themify: layout-grid4-alt' => 'ti-layout-grid4-alt',
			'Themify: layout-grid3-alt' => 'ti-layout-grid3-alt',
			'Themify: layout-grid2-alt' => 'ti-layout-grid2-alt',
			'Themify: layout-column4-alt' => 'ti-layout-column4-alt',
			'Themify: layout-column3-alt' => 'ti-layout-column3-alt',
			'Themify: layout-column2-alt' => 'ti-layout-column2-alt',
			'Themify: flickr' => 'ti-flickr',
			'Themify: flickr-alt' => 'ti-flickr-alt',
			'Themify: instagram' => 'ti-instagram',
			'Themify: google' => 'ti-google',
			'Themify: github' => 'ti-github',
			'Themify: facebook' => 'ti-facebook',
			'Themify: dropbox' => 'ti-dropbox',
			'Themify: dropbox-alt' => 'ti-dropbox-alt',
			'Themify: dribbble' => 'ti-dribbble',
			'Themify: apple' => 'ti-apple',
			'Themify: android' => 'ti-android',
			'Themify: yahoo' => 'ti-yahoo',
			'Themify: trello' => 'ti-trello',
			'Themify: stack-overflow' => 'ti-stack-overflow',
			'Themify: soundcloud' => 'ti-soundcloud',
			'Themify: sharethis' => 'ti-sharethis',
			'Themify: sharethis-alt' => 'ti-sharethis-alt',
			'Themify: reddit' => 'ti-reddit',
			'Themify: microsoft' => 'ti-microsoft',
			'Themify: microsoft-alt' => 'ti-microsoft-alt',
			'Themify: linux' => 'ti-linux',
			'Themify: jsfiddle' => 'ti-jsfiddle',
			'Themify: joomla' => 'ti-joomla',
			'Themify: html5' => 'ti-html5',
			'Themify: css3' => 'ti-css3',
			'Themify: drupal' => 'ti-drupal',
			'Themify: wordpress' => 'ti-wordpress',
			'Themify: tumblr' => 'ti-tumblr',
			'Themify: tumblr-alt' => 'ti-tumblr-alt',
			'Themify: skype' => 'ti-skype',
			'Themify: youtube' => 'ti-youtube',
			'Themify: vimeo' => 'ti-vimeo',
			'Themify: vimeo-alt' => 'ti-vimeo-alt',
			'Themify: twitter' => 'ti-twitter',
			'Themify: twitter-alt' => 'ti-twitter-alt',
			'Themify: linkedin' => 'ti-linkedin',
			'Themify: pinterest' => 'ti-pinterest',
			'Themify: pinterest-alt' => 'ti-pinterest-alt',
			'Themify: themify-logo' => 'ti-themify-logo',
			'Themify: themify-favicon' => 'ti-themify-favicon',
			'Themify: themify-favicon-alt' => 'ti-themify-favicon-alt',
		),
        array(		
			'FontAwesome: glass' => 'fa fa-glass',
			'FontAwesome: music' => 'fa fa-music',
			'FontAwesome: search' => 'fa fa-search',
			'FontAwesome: envelope-o' => 'fa fa-envelope-o',
			'FontAwesome: heart' => 'fa fa-heart',
			'FontAwesome: star' => 'fa fa-star',
			'FontAwesome: star-o' => 'fa fa-star-o',
			'FontAwesome: user' => 'fa fa-user',
			'FontAwesome: film' => 'fa fa-film',
			'FontAwesome: th-large' => 'fa fa-th-large',
			'FontAwesome: th' => 'fa fa-th',
			'FontAwesome: th-list' => 'fa fa-th-list',
			'FontAwesome: check' => 'fa fa-check',
			'FontAwesome: times' => 'fa fa-times',
			'FontAwesome: search-plus' => 'fa fa-search-plus',
			'FontAwesome: search-minus' => 'fa fa-search-minus',
			'FontAwesome: power-off' => 'fa fa-power-off',
			'FontAwesome: signal' => 'fa fa-signal',
			'FontAwesome: gear' => 'fa fa-gear',
			'FontAwesome: cog' => 'fa fa-cog',
			'FontAwesome: trash-o' => 'fa fa-trash-o',
			'FontAwesome: home' => 'fa fa-home',
			'FontAwesome: file-o' => 'fa fa-file-o',
			'FontAwesome: clock-o' => 'fa fa-clock-o',
			'FontAwesome: road' => 'fa fa-road',
			'FontAwesome: download' => 'fa fa-download',
			'FontAwesome: arrow-circle-o-down' => 'fa fa-arrow-circle-o-down',
			'FontAwesome: arrow-circle-o-up' => 'fa fa-arrow-circle-o-up',
			'FontAwesome: inbox' => 'fa fa-inbox',
			'FontAwesome: play-circle-o' => 'fa fa-play-circle-o',
			'FontAwesome: rotate-right' => 'fa fa-rotate-right',
			'FontAwesome: repeat' => 'fa fa-repeat',
			'FontAwesome: refresh' => 'fa fa-refresh',
			'FontAwesome: list-alt' => 'fa fa-list-alt',
			'FontAwesome: lock' => 'fa fa-lock',
			'FontAwesome: flag' => 'fa fa-flag',
			'FontAwesome: headphones' => 'fa fa-headphones',
			'FontAwesome: volume-off' => 'fa fa-volume-off',
			'FontAwesome: volume-down' => 'fa fa-volume-down',
			'FontAwesome: volume-up' => 'fa fa-volume-up',
			'FontAwesome: qrcode' => 'fa fa-qrcode',
			'FontAwesome: barcode' => 'fa fa-barcode',
			'FontAwesome: tag' => 'fa fa-tag',
			'FontAwesome: tags' => 'fa fa-tags',
			'FontAwesome: book' => 'fa fa-book',
			'FontAwesome: bookmark' => 'fa fa-bookmark',
			'FontAwesome: print' => 'fa fa-print',
			'FontAwesome: camera' => 'fa fa-camera',
			'FontAwesome: font' => 'fa fa-font',
			'FontAwesome: bold' => 'fa fa-bold',
			'FontAwesome: italic' => 'fa fa-italic',
			'FontAwesome: text-height' => 'fa fa-text-height',
			'FontAwesome: text-width' => 'fa fa-text-width',
			'FontAwesome: align-left' => 'fa fa-align-left',
			'FontAwesome: align-center' => 'fa fa-align-center',
			'FontAwesome: align-right' => 'fa fa-align-right',
			'FontAwesome: align-justify' => 'fa fa-align-justify',
			'FontAwesome: list' => 'fa fa-list',
			'FontAwesome: dedent' => 'fa fa-dedent',
			'FontAwesome: outdent' => 'fa fa-outdent',
			'FontAwesome: indent' => 'fa fa-indent',
			'FontAwesome: video-camera' => 'fa fa-video-camera',
			'FontAwesome: photo' => 'fa fa-photo',
			'FontAwesome: image' => 'fa fa-image',
			'FontAwesome: picture-o' => 'fa fa-picture-o',
			'FontAwesome: pencil' => 'fa fa-pencil',
			'FontAwesome: map-marker' => 'fa fa-map-marker',
			'FontAwesome: adjust' => 'fa fa-adjust',
			'FontAwesome: tint' => 'fa fa-tint',
			'FontAwesome: edit' => 'fa fa-edit',
			'FontAwesome: pencil-square-o' => 'fa fa-pencil-square-o',
			'FontAwesome: share-square-o' => 'fa fa-share-square-o',
			'FontAwesome: check-square-o' => 'fa fa-check-square-o',
			'FontAwesome: arrows' => 'fa fa-arrows',
			'FontAwesome: step-backward' => 'fa fa-step-backward',
			'FontAwesome: fast-backward' => 'fa fa-fast-backward',
			'FontAwesome: backward' => 'fa fa-backward',
			'FontAwesome: play' => 'fa fa-play',
			'FontAwesome: pause' => 'fa fa-pause',
			'FontAwesome: stop' => 'fa fa-stop',
			'FontAwesome: forward' => 'fa fa-forward',
			'FontAwesome: fast-forward' => 'fa fa-fast-forward',
			'FontAwesome: step-forward' => 'fa fa-step-forward',
			'FontAwesome: eject' => 'fa fa-eject',
			'FontAwesome: chevron-left' => 'fa fa-chevron-left',
			'FontAwesome: chevron-right' => 'fa fa-chevron-right',
			'FontAwesome: plus-circle' => 'fa fa-plus-circle',
			'FontAwesome: minus-circle' => 'fa fa-minus-circle',
			'FontAwesome: times-circle' => 'fa fa-times-circle',
			'FontAwesome: check-circle' => 'fa fa-check-circle',
			'FontAwesome: question-circle' => 'fa fa-question-circle',
			'FontAwesome: info-circle' => 'fa fa-info-circle',
			'FontAwesome: crosshairs' => 'fa fa-crosshairs',
			'FontAwesome: times-circle-o' => 'fa fa-times-circle-o',
			'FontAwesome: check-circle-o' => 'fa fa-check-circle-o',
			'FontAwesome: ban' => 'fa fa-ban',
			'FontAwesome: arrow-left' => 'fa fa-arrow-left',
			'FontAwesome: arrow-right' => 'fa fa-arrow-right',
			'FontAwesome: arrow-up' => 'fa fa-arrow-up',
			'FontAwesome: arrow-down' => 'fa fa-arrow-down',
			'FontAwesome: mail-forward' => 'fa fa-mail-forward',
			'FontAwesome: share' => 'fa fa-share',
			'FontAwesome: expand' => 'fa fa-expand',
			'FontAwesome: compress' => 'fa fa-compress',
			'FontAwesome: plus' => 'fa fa-plus',
			'FontAwesome: minus' => 'fa fa-minus',
			'FontAwesome: asterisk' => 'fa fa-asterisk',
			'FontAwesome: exclamation-circle' => 'fa fa-exclamation-circle',
			'FontAwesome: gift' => 'fa fa-gift',
			'FontAwesome: leaf' => 'fa fa-leaf',
			'FontAwesome: fire' => 'fa fa-fire',
			'FontAwesome: eye' => 'fa fa-eye',
			'FontAwesome: eye-slash' => 'fa fa-eye-slash',
			'FontAwesome: warning' => 'fa fa-warning',
			'FontAwesome: exclamation-triangle' => 'fa fa-exclamation-triangle',
			'FontAwesome: plane' => 'fa fa-plane',
			'FontAwesome: calendar' => 'fa fa-calendar',
			'FontAwesome: random' => 'fa fa-random',
			'FontAwesome: comment' => 'fa fa-comment',
			'FontAwesome: magnet' => 'fa fa-magnet',
			'FontAwesome: chevron-up' => 'fa fa-chevron-up',
			'FontAwesome: chevron-down' => 'fa fa-chevron-down',
			'FontAwesome: retweet' => 'fa fa-retweet',
			'FontAwesome: shopping-cart' => 'fa fa-shopping-cart',
			'FontAwesome: folder' => 'fa fa-folder',
			'FontAwesome: folder-open' => 'fa fa-folder-open',
			'FontAwesome: arrows-v' => 'fa fa-arrows-v',
			'FontAwesome: arrows-h' => 'fa fa-arrows-h',
			'FontAwesome: bar-chart-o' => 'fa fa-bar-chart-o',
			'FontAwesome: twitter-square' => 'fa fa-twitter-square',
			'FontAwesome: facebook-square' => 'fa fa-facebook-square',
			'FontAwesome: camera-retro' => 'fa fa-camera-retro',
			'FontAwesome: key' => 'fa fa-key',
			'FontAwesome: gears' => 'fa fa-gears',
			'FontAwesome: cogs' => 'fa fa-cogs',
			'FontAwesome: comments' => 'fa fa-comments',
			'FontAwesome: thumbs-o-up' => 'fa fa-thumbs-o-up',
			'FontAwesome: thumbs-o-down' => 'fa fa-thumbs-o-down',
			'FontAwesome: star-half' => 'fa fa-star-half',
			'FontAwesome: heart-o' => 'fa fa-heart-o',
			'FontAwesome: sign-out' => 'fa fa-sign-out',
			'FontAwesome: linkedin-square' => 'fa fa-linkedin-square',
			'FontAwesome: thumb-tack' => 'fa fa-thumb-tack',
			'FontAwesome: external-link' => 'fa fa-external-link',
			'FontAwesome: sign-in' => 'fa fa-sign-in',
			'FontAwesome: trophy' => 'fa fa-trophy',
			'FontAwesome: github-square' => 'fa fa-github-square',
			'FontAwesome: upload' => 'fa fa-upload',
			'FontAwesome: lemon-o' => 'fa fa-lemon-o',
			'FontAwesome: phone' => 'fa fa-phone',
			'FontAwesome: square-o' => 'fa fa-square-o',
			'FontAwesome: bookmark-o' => 'fa fa-bookmark-o',
			'FontAwesome: phone-square' => 'fa fa-phone-square',
			'FontAwesome: twitter' => 'fa fa-twitter',
			'FontAwesome: facebook' => 'fa fa-facebook',
			'FontAwesome: github' => 'fa fa-github',
			'FontAwesome: unlock' => 'fa fa-unlock',
			'FontAwesome: credit-card' => 'fa fa-credit-card',
			'FontAwesome: rss' => 'fa fa-rss',
			'FontAwesome: hdd-o' => 'fa fa-hdd-o',
			'FontAwesome: bullhorn' => 'fa fa-bullhorn',
			'FontAwesome: bell' => 'fa fa-bell',
			'FontAwesome: certificate' => 'fa fa-certificate',
			'FontAwesome: hand-o-right' => 'fa fa-hand-o-right',
			'FontAwesome: hand-o-left' => 'fa fa-hand-o-left',
			'FontAwesome: hand-o-up' => 'fa fa-hand-o-up',
			'FontAwesome: hand-o-down' => 'fa fa-hand-o-down',
			'FontAwesome: arrow-circle-left' => 'fa fa-arrow-circle-left',
			'FontAwesome: arrow-circle-right' => 'fa fa-arrow-circle-right',
			'FontAwesome: arrow-circle-up' => 'fa fa-arrow-circle-up',
			'FontAwesome: arrow-circle-down' => 'fa fa-arrow-circle-down',
			'FontAwesome: globe' => 'fa fa-globe',
			'FontAwesome: wrench' => 'fa fa-wrench',
			'FontAwesome: tasks' => 'fa fa-tasks',
			'FontAwesome: filter' => 'fa fa-filter',
			'FontAwesome: briefcase' => 'fa fa-briefcase',
			'FontAwesome: arrows-alt' => 'fa fa-arrows-alt',
			'FontAwesome: group' => 'fa fa-group',
			'FontAwesome: users' => 'fa fa-users',
			'FontAwesome: chain' => 'fa fa-chain',
			'FontAwesome: link' => 'fa fa-link',
			'FontAwesome: cloud' => 'fa fa-cloud',
			'FontAwesome: flask' => 'fa fa-flask',
			'FontAwesome: cut' => 'fa fa-cut',
			'FontAwesome: scissors' => 'fa fa-scissors',
			'FontAwesome: copy' => 'fa fa-copy',
			'FontAwesome: files-o' => 'fa fa-files-o',
			'FontAwesome: paperclip' => 'fa fa-paperclip',
			'FontAwesome: save' => 'fa fa-save',
			'FontAwesome: floppy-o' => 'fa fa-floppy-o',
			'FontAwesome: square' => 'fa fa-square',
			'FontAwesome: navicon' => 'fa fa-navicon',
			'FontAwesome: reorder' => 'fa fa-reorder',
			'FontAwesome: bars' => 'fa fa-bars',
			'FontAwesome: list-ul' => 'fa fa-list-ul',
			'FontAwesome: list-ol' => 'fa fa-list-ol',
			'FontAwesome: strikethrough' => 'fa fa-strikethrough',
			'FontAwesome: underline' => 'fa fa-underline',
			'FontAwesome: table' => 'fa fa-table',
			'FontAwesome: magic' => 'fa fa-magic',
			'FontAwesome: truck' => 'fa fa-truck',
			'FontAwesome: pinterest' => 'fa fa-pinterest',
			'FontAwesome: pinterest-square' => 'fa fa-pinterest-square',
			'FontAwesome: google-plus-square' => 'fa fa-google-plus-square',
			'FontAwesome: google-plus' => 'fa fa-google-plus',
			'FontAwesome: money' => 'fa fa-money',
			'FontAwesome: caret-down' => 'fa fa-caret-down',
			'FontAwesome: caret-up' => 'fa fa-caret-up',
			'FontAwesome: caret-left' => 'fa fa-caret-left',
			'FontAwesome: caret-right' => 'fa fa-caret-right',
			'FontAwesome: columns' => 'fa fa-columns',
			'FontAwesome: unsorted' => 'fa fa-unsorted',
			'FontAwesome: sort' => 'fa fa-sort',
			'FontAwesome: sort-down' => 'fa fa-sort-down',
			'FontAwesome: sort-desc' => 'fa fa-sort-desc',
			'FontAwesome: sort-up' => 'fa fa-sort-up',
			'FontAwesome: sort-asc' => 'fa fa-sort-asc',
			'FontAwesome: envelope' => 'fa fa-envelope',
			'FontAwesome: linkedin' => 'fa fa-linkedin',
			'FontAwesome: rotate-left' => 'fa fa-rotate-left',
			'FontAwesome: undo' => 'fa fa-undo',
			'FontAwesome: legal' => 'fa fa-legal',
			'FontAwesome: gavel' => 'fa fa-gavel',
			'FontAwesome: dashboard' => 'fa fa-dashboard',
			'FontAwesome: tachometer' => 'fa fa-tachometer',
			'FontAwesome: comment-o' => 'fa fa-comment-o',
			'FontAwesome: comments-o' => 'fa fa-comments-o',
			'FontAwesome: flash' => 'fa fa-flash',
			'FontAwesome: bolt' => 'fa fa-bolt',
			'FontAwesome: sitemap' => 'fa fa-sitemap',
			'FontAwesome: umbrella' => 'fa fa-umbrella',
			'FontAwesome: paste' => 'fa fa-paste',
			'FontAwesome: clipboard' => 'fa fa-clipboard',
			'FontAwesome: lightbulb-o' => 'fa fa-lightbulb-o',
			'FontAwesome: exchange' => 'fa fa-exchange',
			'FontAwesome: cloud-download' => 'fa fa-cloud-download',
			'FontAwesome: cloud-upload' => 'fa fa-cloud-upload',
			'FontAwesome: user-md' => 'fa fa-user-md',
			'FontAwesome: stethoscope' => 'fa fa-stethoscope',
			'FontAwesome: suitcase' => 'fa fa-suitcase',
			'FontAwesome: bell-o' => 'fa fa-bell-o',
			'FontAwesome: coffee' => 'fa fa-coffee',
			'FontAwesome: cutlery' => 'fa fa-cutlery',
			'FontAwesome: file-text-o' => 'fa fa-file-text-o',
			'FontAwesome: building-o' => 'fa fa-building-o',
			'FontAwesome: hospital-o' => 'fa fa-hospital-o',
			'FontAwesome: ambulance' => 'fa fa-ambulance',
			'FontAwesome: medkit' => 'fa fa-medkit',
			'FontAwesome: fighter-jet' => 'fa fa-fighter-jet',
			'FontAwesome: beer' => 'fa fa-beer',
			'FontAwesome: h-square' => 'fa fa-h-square',
			'FontAwesome: plus-square' => 'fa fa-plus-square',
			'FontAwesome: angle-double-left' => 'fa fa-angle-double-left',
			'FontAwesome: angle-double-right' => 'fa fa-angle-double-right',
			'FontAwesome: angle-double-up' => 'fa fa-angle-double-up',
			'FontAwesome: angle-double-down' => 'fa fa-angle-double-down',
			'FontAwesome: angle-left' => 'fa fa-angle-left',
			'FontAwesome: angle-right' => 'fa fa-angle-right',
			'FontAwesome: angle-up' => 'fa fa-angle-up',
			'FontAwesome: angle-down' => 'fa fa-angle-down',
			'FontAwesome: desktop' => 'fa fa-desktop',
			'FontAwesome: laptop' => 'fa fa-laptop',
			'FontAwesome: tablet' => 'fa fa-tablet',
			'FontAwesome: mobile-phone' => 'fa fa-mobile-phone',
			'FontAwesome: mobile' => 'fa fa-mobile',
			'FontAwesome: circle-o' => 'fa fa-circle-o',
			'FontAwesome: quote-left' => 'fa fa-quote-left',
			'FontAwesome: quote-right' => 'fa fa-quote-right',
			'FontAwesome: spinner' => 'fa fa-spinner',
			'FontAwesome: circle' => 'fa fa-circle',
			'FontAwesome: mail-reply' => 'fa fa-mail-reply',
			'FontAwesome: reply' => 'fa fa-reply',
			'FontAwesome: github-alt' => 'fa fa-github-alt',
			'FontAwesome: folder-o' => 'fa fa-folder-o',
			'FontAwesome: folder-open-o' => 'fa fa-folder-open-o',
			'FontAwesome: smile-o' => 'fa fa-smile-o',
			'FontAwesome: frown-o' => 'fa fa-frown-o',
			'FontAwesome: meh-o' => 'fa fa-meh-o',
			'FontAwesome: gamepad' => 'fa fa-gamepad',
			'FontAwesome: keyboard-o' => 'fa fa-keyboard-o',
			'FontAwesome: flag-o' => 'fa fa-flag-o',
			'FontAwesome: flag-checkered' => 'fa fa-flag-checkered',
			'FontAwesome: terminal' => 'fa fa-terminal',
			'FontAwesome: code' => 'fa fa-code',
			'FontAwesome: mail-reply-all' => 'fa fa-mail-reply-all',
			'FontAwesome: reply-all' => 'fa fa-reply-all',
			'FontAwesome: star-half-empty' => 'fa fa-star-half-empty',
			'FontAwesome: star-half-full' => 'fa fa-star-half-full',
			'FontAwesome: star-half-o' => 'fa fa-star-half-o',
			'FontAwesome: location-arrow' => 'fa fa-location-arrow',
			'FontAwesome: crop' => 'fa fa-crop',
			'FontAwesome: code-fork' => 'fa fa-code-fork',
			'FontAwesome: unlink' => 'fa fa-unlink',
			'FontAwesome: chain-broken' => 'fa fa-chain-broken',
			'FontAwesome: question' => 'fa fa-question',
			'FontAwesome: info' => 'fa fa-info',
			'FontAwesome: exclamation' => 'fa fa-exclamation',
			'FontAwesome: superscript' => 'fa fa-superscript',
			'FontAwesome: subscript' => 'fa fa-subscript',
			'FontAwesome: eraser' => 'fa fa-eraser',
			'FontAwesome: puzzle-piece' => 'fa fa-puzzle-piece',
			'FontAwesome: microphone' => 'fa fa-microphone',
			'FontAwesome: microphone-slash' => 'fa fa-microphone-slash',
			'FontAwesome: shield' => 'fa fa-shield',
			'FontAwesome: calendar-o' => 'fa fa-calendar-o',
			'FontAwesome: fire-extinguisher' => 'fa fa-fire-extinguisher',
			'FontAwesome: rocket' => 'fa fa-rocket',
			'FontAwesome: maxcdn' => 'fa fa-maxcdn',
			'FontAwesome: chevron-circle-left' => 'fa fa-chevron-circle-left',
			'FontAwesome: chevron-circle-right' => 'fa fa-chevron-circle-right',
			'FontAwesome: chevron-circle-up' => 'fa fa-chevron-circle-up',
			'FontAwesome: chevron-circle-down' => 'fa fa-chevron-circle-down',
			'FontAwesome: html5' => 'fa fa-html5',
			'FontAwesome: css3' => 'fa fa-css3',
			'FontAwesome: anchor' => 'fa fa-anchor',
			'FontAwesome: unlock-alt' => 'fa fa-unlock-alt',
			'FontAwesome: bullseye' => 'fa fa-bullseye',
			'FontAwesome: ellipsis-h' => 'fa fa-ellipsis-h',
			'FontAwesome: ellipsis-v' => 'fa fa-ellipsis-v',
			'FontAwesome: rss-square' => 'fa fa-rss-square',
			'FontAwesome: play-circle' => 'fa fa-play-circle',
			'FontAwesome: ticket' => 'fa fa-ticket',
			'FontAwesome: minus-square' => 'fa fa-minus-square',
			'FontAwesome: minus-square-o' => 'fa fa-minus-square-o',
			'FontAwesome: level-up' => 'fa fa-level-up',
			'FontAwesome: level-down' => 'fa fa-level-down',
			'FontAwesome: check-square' => 'fa fa-check-square',
			'FontAwesome: pencil-square' => 'fa fa-pencil-square',
			'FontAwesome: external-link-square' => 'fa fa-external-link-square',
			'FontAwesome: share-square' => 'fa fa-share-square',
			'FontAwesome: compass' => 'fa fa-compass',
			'FontAwesome: toggle-down' => 'fa fa-toggle-down',
			'FontAwesome: caret-square-o-down' => 'fa fa-caret-square-o-down',
			'FontAwesome: toggle-up' => 'fa fa-toggle-up',
			'FontAwesome: caret-square-o-up' => 'fa fa-caret-square-o-up',
			'FontAwesome: toggle-right' => 'fa fa-toggle-right',
			'FontAwesome: caret-square-o-right' => 'fa fa-caret-square-o-right',
			'FontAwesome: euro' => 'fa fa-euro',
			'FontAwesome: eur' => 'fa fa-eur',
			'FontAwesome: gbp' => 'fa fa-gbp',
			'FontAwesome: dollar' => 'fa fa-dollar',
			'FontAwesome: usd' => 'fa fa-usd',
			'FontAwesome: rupee' => 'fa fa-rupee',
			'FontAwesome: inr' => 'fa fa-inr',
			'FontAwesome: cny' => 'fa fa-cny',
			'FontAwesome: rmb' => 'fa fa-rmb',
			'FontAwesome: yen' => 'fa fa-yen',
			'FontAwesome: jpy' => 'fa fa-jpy',
			'FontAwesome: ruble' => 'fa fa-ruble',
			'FontAwesome: rouble' => 'fa fa-rouble',
			'FontAwesome: rub' => 'fa fa-rub',
			'FontAwesome: won' => 'fa fa-won',
			'FontAwesome: krw' => 'fa fa-krw',
			'FontAwesome: bitcoin' => 'fa fa-bitcoin',
			'FontAwesome: btc' => 'fa fa-btc',
			'FontAwesome: file' => 'fa fa-file',
			'FontAwesome: file-text' => 'fa fa-file-text',
			'FontAwesome: sort-alpha-asc' => 'fa fa-sort-alpha-asc',
			'FontAwesome: sort-alpha-desc' => 'fa fa-sort-alpha-desc',
			'FontAwesome: sort-amount-asc' => 'fa fa-sort-amount-asc',
			'FontAwesome: sort-amount-desc' => 'fa fa-sort-amount-desc',
			'FontAwesome: sort-numeric-asc' => 'fa fa-sort-numeric-asc',
			'FontAwesome: sort-numeric-desc' => 'fa fa-sort-numeric-desc',
			'FontAwesome: thumbs-up' => 'fa fa-thumbs-up',
			'FontAwesome: thumbs-down' => 'fa fa-thumbs-down',
			'FontAwesome: youtube-square' => 'fa fa-youtube-square',
			'FontAwesome: youtube' => 'fa fa-youtube',
			'FontAwesome: xing' => 'fa fa-xing',
			'FontAwesome: xing-square' => 'fa fa-xing-square',
			'FontAwesome: youtube-play' => 'fa fa-youtube-play',
			'FontAwesome: dropbox' => 'fa fa-dropbox',
			'FontAwesome: stack-overflow' => 'fa fa-stack-overflow',
			'FontAwesome: instagram' => 'fa fa-instagram',
			'FontAwesome: flickr' => 'fa fa-flickr',
			'FontAwesome: adn' => 'fa fa-adn',
			'FontAwesome: bitbucket' => 'fa fa-bitbucket',
			'FontAwesome: bitbucket-square' => 'fa fa-bitbucket-square',
			'FontAwesome: tumblr' => 'fa fa-tumblr',
			'FontAwesome: tumblr-square' => 'fa fa-tumblr-square',
			'FontAwesome: long-arrow-down' => 'fa fa-long-arrow-down',
			'FontAwesome: long-arrow-up' => 'fa fa-long-arrow-up',
			'FontAwesome: long-arrow-left' => 'fa fa-long-arrow-left',
			'FontAwesome: long-arrow-right' => 'fa fa-long-arrow-right',
			'FontAwesome: apple' => 'fa fa-apple',
			'FontAwesome: windows' => 'fa fa-windows',
			'FontAwesome: android' => 'fa fa-android',
			'FontAwesome: linux' => 'fa fa-linux',
			'FontAwesome: dribbble' => 'fa fa-dribbble',
			'FontAwesome: skype' => 'fa fa-skype',
			'FontAwesome: foursquare' => 'fa fa-foursquare',
			'FontAwesome: trello' => 'fa fa-trello',
			'FontAwesome: female' => 'fa fa-female',
			'FontAwesome: male' => 'fa fa-male',
			'FontAwesome: gittip' => 'fa fa-gittip',
			'FontAwesome: sun-o' => 'fa fa-sun-o',
			'FontAwesome: moon-o' => 'fa fa-moon-o',
			'FontAwesome: archive' => 'fa fa-archive',
			'FontAwesome: bug' => 'fa fa-bug',
			'FontAwesome: vk' => 'fa fa-vk',
			'FontAwesome: weibo' => 'fa fa-weibo',
			'FontAwesome: renren' => 'fa fa-renren',
			'FontAwesome: pagelines' => 'fa fa-pagelines',
			'FontAwesome: stack-exchange' => 'fa fa-stack-exchange',
			'FontAwesome: arrow-circle-o-right' => 'fa fa-arrow-circle-o-right',
			'FontAwesome: arrow-circle-o-left' => 'fa fa-arrow-circle-o-left',
			'FontAwesome: toggle-left' => 'fa fa-toggle-left',
			'FontAwesome: caret-square-o-left' => 'fa fa-caret-square-o-left',
			'FontAwesome: dot-circle-o' => 'fa fa-dot-circle-o',
			'FontAwesome: wheelchair' => 'fa fa-wheelchair',
			'FontAwesome: vimeo-square' => 'fa fa-vimeo-square',
			'FontAwesome: turkish-lira' => 'fa fa-turkish-lira',
			'FontAwesome: try' => 'fa fa-try',
			'FontAwesome: plus-square-o' => 'fa fa-plus-square-o',
			'FontAwesome: space-shuttle' => 'fa fa-space-shuttle',
			'FontAwesome: slack' => 'fa fa-slack',
			'FontAwesome: envelope-square' => 'fa fa-envelope-square',
			'FontAwesome: wordpress' => 'fa fa-wordpress',
			'FontAwesome: openid' => 'fa fa-openid',
			'FontAwesome: institution' => 'fa fa-institution',
			'FontAwesome: bank' => 'fa fa-bank',
			'FontAwesome: university' => 'fa fa-university',
			'FontAwesome: mortar-board' => 'fa fa-mortar-board',
			'FontAwesome: graduation-cap' => 'fa fa-graduation-cap',
			'FontAwesome: yahoo' => 'fa fa-yahoo',
			'FontAwesome: google' => 'fa fa-google',
			'FontAwesome: reddit' => 'fa fa-reddit',
			'FontAwesome: reddit-square' => 'fa fa-reddit-square',
			'FontAwesome: stumbleupon-circle' => 'fa fa-stumbleupon-circle',
			'FontAwesome: stumbleupon' => 'fa fa-stumbleupon',
			'FontAwesome: delicious' => 'fa fa-delicious',
			'FontAwesome: digg' => 'fa fa-digg',
			'FontAwesome: pied-piper-square' => 'fa fa-pied-piper-square',
			'FontAwesome: pied-piper' => 'fa fa-pied-piper',
			'FontAwesome: pied-piper-alt' => 'fa fa-pied-piper-alt',
			'FontAwesome: drupal' => 'fa fa-drupal',
			'FontAwesome: joomla' => 'fa fa-joomla',
			'FontAwesome: language' => 'fa fa-language',
			'FontAwesome: fax' => 'fa fa-fax',
			'FontAwesome: building' => 'fa fa-building',
			'FontAwesome: child' => 'fa fa-child',
			'FontAwesome: paw' => 'fa fa-paw',
			'FontAwesome: spoon' => 'fa fa-spoon',
			'FontAwesome: cube' => 'fa fa-cube',
			'FontAwesome: cubes' => 'fa fa-cubes',
			'FontAwesome: behance' => 'fa fa-behance',
			'FontAwesome: behance-square' => 'fa fa-behance-square',
			'FontAwesome: steam' => 'fa fa-steam',
			'FontAwesome: steam-square' => 'fa fa-steam-square',
			'FontAwesome: recycle' => 'fa fa-recycle',
			'FontAwesome: automobile' => 'fa fa-automobile',
			'FontAwesome: car' => 'fa fa-car',
			'FontAwesome: cab' => 'fa fa-cab',
			'FontAwesome: taxi' => 'fa fa-taxi',
			'FontAwesome: tree' => 'fa fa-tree',
			'FontAwesome: spotify' => 'fa fa-spotify',
			'FontAwesome: deviantart' => 'fa fa-deviantart',
			'FontAwesome: soundcloud' => 'fa fa-soundcloud',
			'FontAwesome: database' => 'fa fa-database',
			'FontAwesome: file-pdf-o' => 'fa fa-file-pdf-o',
			'FontAwesome: file-word-o' => 'fa fa-file-word-o',
			'FontAwesome: file-excel-o' => 'fa fa-file-excel-o',
			'FontAwesome: file-powerpoint-o' => 'fa fa-file-powerpoint-o',
			'FontAwesome: file-photo-o' => 'fa fa-file-photo-o',
			'FontAwesome: file-picture-o' => 'fa fa-file-picture-o',
			'FontAwesome: file-image-o' => 'fa fa-file-image-o',
			'FontAwesome: file-zip-o' => 'fa fa-file-zip-o',
			'FontAwesome: file-archive-o' => 'fa fa-file-archive-o',
			'FontAwesome: file-sound-o' => 'fa fa-file-sound-o',
			'FontAwesome: file-audio-o' => 'fa fa-file-audio-o',
			'FontAwesome: file-movie-o' => 'fa fa-file-movie-o',
			'FontAwesome: file-video-o' => 'fa fa-file-video-o',
			'FontAwesome: file-code-o' => 'fa fa-file-code-o',
			'FontAwesome: vine' => 'fa fa-vine',
			'FontAwesome: codepen' => 'fa fa-codepen',
			'FontAwesome: jsfiddle' => 'fa fa-jsfiddle',
			'FontAwesome: life-bouy' => 'fa fa-life-bouy',
			'FontAwesome: life-saver' => 'fa fa-life-saver',
			'FontAwesome: support' => 'fa fa-support',
			'FontAwesome: life-ring' => 'fa fa-life-ring',
			'FontAwesome: circle-o-notch' => 'fa fa-circle-o-notch',
			'FontAwesome: ra' => 'fa fa-ra',
			'FontAwesome: rebel' => 'fa fa-rebel',
			'FontAwesome: ge' => 'fa fa-ge',
			'FontAwesome: empire' => 'fa fa-empire',
			'FontAwesome: git-square' => 'fa fa-git-square',
			'FontAwesome: git' => 'fa fa-git',
			'FontAwesome: hacker-news' => 'fa fa-hacker-news',
			'FontAwesome: tencent-weibo' => 'fa fa-tencent-weibo',
			'FontAwesome: qq' => 'fa fa-qq',
			'FontAwesome: wechat' => 'fa fa-wechat',
			'FontAwesome: weixin' => 'fa fa-weixin',
			'FontAwesome: send' => 'fa fa-send',
			'FontAwesome: paper-plane' => 'fa fa-paper-plane',
			'FontAwesome: send-o' => 'fa fa-send-o',
			'FontAwesome: paper-plane-o' => 'fa fa-paper-plane-o',
			'FontAwesome: history' => 'fa fa-history',
			'FontAwesome: circle-thin' => 'fa fa-circle-thin',
			'FontAwesome: header' => 'fa fa-header',
			'FontAwesome: paragraph' => 'fa fa-paragraph',
			'FontAwesome: sliders' => 'fa fa-sliders',
			'FontAwesome: share-alt' => 'fa fa-share-alt',
			'FontAwesome: share-alt-square' => 'fa fa-share-alt-square',
			'FontAwesome: bomb' => 'fa fa-bomb',
		)
    );
}

/**
 * Background Overlay
 */
function codebean_data_source_background_overlay() {
	return array(
		array(
			'label' => esc_html__( 'none', 'onliestwp' ),
			'value' => '',
		),
		array(
			'label' => esc_html__( 'black overlay', 'onliestwp' ),
			'value' => 'black-overlay',
		),
		array(
			'label' => esc_html__( 'dotted overlay', 'onliestwp' ),
			'value' => 'dotted-overlay',
		),
	);
}

/**
 * Background Repeat
 */
function codebean_data_source_background_repeat() {
	return array(
		array(
			'label' => esc_html__( 'default', 'onliestwp' ),
			'value' => '',
		),
		array(
			'label' => esc_html__( 'cover', 'onliestwp' ),
			'value' => 'cover',
		),
		array(
			'label' => esc_html__( 'contain', 'onliestwp' ),
			'value' => 'contain',
		),
		array(
			'label' => esc_html__( 'no repeat', 'onliestwp' ),
			'value' => 'no-repeat',
		),
	);
}