<?php


if ( function_exists( 'register_field_group' ) )
{

    register_field_group( array(
        'id' => 'acf_page-options',
        'title' => esc_html__( 'Page Options', 'onliestwp' ),
        'fields' => array(
            array (
                'key' => 'field_544fd30acf7d3',
                'label' => esc_html__( 'Show Page Title', 'onliestwp' ),
                'instructions' => esc_html__( 'Show or hide page title.', 'onliestwp' ),
                'name' => 'hide_page_title',
                'type' => 'true_false',
                'message' => '',
                'default_value' => 1,
            ),
            array(
                'key' => 'field_322fd40bce38d',
                'label' => esc_html__( 'Show/Hide Slider?', 'onliestwp' ),
                'instructions' => esc_html__( 'If you would like to display Revolution Slider on top of this page, check this!', 'onliestwp' ),
                'message' => esc_html__( 'Yes', 'onliestwp' ),
                'name' => 'show_rev_slider',
                'type' => 'true_false',
                'default_value' => false
            ),
            array(
                'key' => 'field_544fd40bcf64e',
                'label' => esc_html__( 'The Slider', 'onliestwp' ),
                'instructions' => esc_html__( 'Select your slider.', 'onliestwp' ),
                'name' => 'rev_slider',
                'type' => 'select',
                'default_value' => '',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_322fd40bce38d',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                    'allorany' => 'all',
                ),
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'page',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'normal',
            'layout' => 'default',
            'hide_on_screen' => array (
            ),
        ),
        'menu_order' => 0,
    ) );

    register_field_group( array(
        'id' => 'acf_portfolio-options',
        'title' => esc_html__( 'Portfolio Options', 'onliestwp' ),
        'fields' => array(
            array (
                'key' => 'field_54ff2a9a91b43',
                'label' => esc_html__( 'Main Settings', 'onliestwp' ),
                'name' => '',
                'type' => 'tab',
            ),
            array (
                'key' => 'field_364fe40alr234',
                'label' => esc_html__( 'Portfolio Type', 'onliestwp' ),
                'instructions' => esc_html__( 'Select your portfoli style below.', 'onliestwp' ),
                'name' => 'portfolio_type',
                'type' => 'radio',
                'choices' => array(
                    'single-1' => 'Side Portfolio',
                    'single-2' => 'Columned',
                    'single-3' => 'Carousel',
                    'single-4' => 'WPBakery Page Builder',
                ),
                'message' => '',
                'default_value' => 'single-1',
                'allow_null' => 0,
                'multiple' => 0,
            ),
            array (
                'key' => 'field_54cb9c2d4d383',
                'label' => esc_html__( 'Sub Title', 'onliestwp' ),
                'name' => 'sub_title',
                'type' => 'text',
                'instructions' => esc_html__( 'One line title to describe the item (optional).', 'onliestwp' ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_364fe40alr234',
                            'operator' => '!=',
                            'value' => 'single-4',
                        ),
                    ),
                    'allorany' => 'all',
                ),
            ),
            array (
                'key' => 'field_54c8cd2c53942',
                'label' => esc_html__( 'Item Description Alignment', 'onliestwp' ),
                'name' => 'item_description_alignment',
                'type' => 'select',
                'instructions' => esc_html__( 'Set the alignment of description block that contains item details.', 'onliestwp' ),
                'choices' => array (
                    'left' => 'Left',
                    'right' => 'Right',
                ),
                'default_value' => 'left',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_364fe40alr234',
                            'operator' => '==',
                            'value' => 'single-1',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'allow_null' => 0,
                'multiple' => 0,
            ),
            array (
                'key' => 'field_54c8cd2c5364e',
                'label' => esc_html__( 'Show Featured Image', 'onliestwp' ),
                'name' => 'show_featured_image',
                'type' => 'true_false',
                'instructions' => esc_html__( 'Check this box if you want to show featured image above the post title..', 'onliestwp' ),
                'message' => esc_html__( 'Yes', 'onliestwp' ),
                'default_value' => false,
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_364fe40alr234',
                            'operator' => '==',
                            'value' => 'single-2',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'allow_null' => 0,
                'multiple' => 0,
            ),
            array (
                'key' => 'field_54ca5e82cfe95',
                'label' => esc_html__( 'Sticky Description', 'onliestwp' ),
                'name' => 'sticky_description',
                'type' => 'true_false',
                'instructions' => esc_html__( 'Make description container sticky when scrolling down the page.', 'onliestwp' ),
                'message' => 'Yes',
                'default_value' => 0,
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_364fe40alr234',
                            'operator' => '==',
                            'value' => 'single-1',
                        ),
                    ),
                    'allorany' => 'all',
                ),
            ),
            array (
                'key' => 'field_54e6448f20eae',
                'label' => esc_html__( 'Checklists', 'onliestwp' ),
                'name' => '',
                'type' => 'tab',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_364fe40alr234',
                            'operator' => '!=',
                            'value' => 'single-4',
                        ),
                    ),
                    'allorany' => 'all',
                ),
            ),
            array (
                'key' => 'field_54cb998106890',
                'label' => esc_html__( 'Checklists', 'onliestwp' ),
                'name' => 'checklists',
                'type' => 'repeater',
                'instructions' => esc_html__( 'Add custom checklists for example the services you have finished, tasks done, etc.', 'onliestwp' ),
                'sub_fields' => array(
                    array (
                        'key' => 'field_54cb99aa06891',
                        'label' => esc_html__( 'Checklist Title', 'onliestwp' ),
                        'name' => 'checklist_title',
                        'type' => 'text',
                        'instructions' => esc_html__( 'Title to describe the checklist items.', 'onliestwp' ),
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'html',
                        'maxlength' => '',
                    ),
                    array (
                        'key' => 'field_54cb99b306892',
                        'label' => esc_html__( 'Checklist', 'onliestwp' ),
                        'name' => 'checklist',
                        'type' => 'textarea',
                        'instructions' => esc_html__( 'Enter one task per line, as many as you want.', 'onliestwp' ),
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => '',
                        'maxlength' => '',
                        'rows' => 5,
                        'formatting' => 'html',
                    ),
                ),
                'row_min' => '',
                'row_limit' => '',
                'layout' => 'row',
                'button_label' => 'New Checklist',
            ),
            array (
                'key' => 'field_54e6448f40c4q',
                'label' => esc_html__( 'Project Link', 'onliestwp' ),
                'name' => '',
                'type' => 'tab',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_364fe40alr234',
                            'operator' => '!=',
                            'value' => 'single-4',
                        ),
                    ),
                    'allorany' => 'all',
                ),
            ),
            array (
                'key' => 'field_54cb9b638f6c0',
                'label' => 'Launch Link Title',
                'name' => 'launch_link_title',
                'type' => 'text',
                'instructions' => 'Usually written "Launch website"',
                'default_value' => 'Launch website',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_54cb9b9a8f6c1',
                'label' => 'Link URL',
                'name' => 'launch_link_href',
                'type' => 'text',
                'instructions' => 'Website when users click in Launch Link (if not given will not be visible to the user).',
                'default_value' => '',
                'placeholder' => 'http://',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_54cb9bab8f6c2',
                'label' => 'Link Target',
                'name' => 'new_window',
                'type' => 'true_false',
                'instructions' => 'Open in new tab or window when user clicks in link.',
                'message' => 'Open in new window',
                'default_value' => 1,
            ),
            array (
                'key' => 'field_55311147850c2',
                'label' => 'Item Linking',
                'name' => 'item_linking',
                'type' => 'select',
                'instructions' => 'Apart from default item single page you can send users to the external source url (optional)',
                'choices' => array (
                    'single' => 'Continue on Single Page',
                    'external' => 'Redirect to Link URL (Project URL)',
                ),
                'default_value' => 'single',
                'allow_null' => 0,
                'multiple' => 0,
            ),
            array (
                'key' => 'field_54e6448f40301',
                'label' => esc_html__( 'Portfolio Gallery', 'onliestwp' ),
                'name' => '',
                'type' => 'tab',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_364fe40alr234',
                            'operator' => '!=',
                            'value' => 'single-4',
                        ),
                    ),
                    'allorany' => 'all',
                ),
            ),
            array (
                'key' => 'field_54cb8fc197f71',
                'label' => esc_html__( 'Gallery', 'onliestwp' ),
                'name' => 'gallery',
                'type' => 'flexible_content',
                'instructions' => esc_html__( 'Select all images you want to show for this portfolio item.', 'onliestwp' ),
                'layouts' => array (
                    array (
                        'label' => 'Image',
                        'name' => 'image',
                        'display' => 'row',
                        'min' => '',
                        'max' => '',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_54cb900997f72',
                                'label' => 'Image',
                                'name' => 'image',
                                'type' => 'image',
                                'instructions' => 'Image that will be shown',
                                'column_width' => 60,
                                'save_format' => 'object',
                                'preview_size' => 'thumbnail',
                                'library' => 'all',
                            ),
                            array (
                                'key' => 'field_54cb903397f73',
                                'label' => 'Column Width',
                                'name' => 'column_width',
                                'type' => 'select',
                                'instructions' => 'Columns for image relative to container',
                                'column_width' => '',
                                'choices' => array (
                                    '1-1' => 'Full width (1/1)',
                                    '1-2' => 'Half width (1/2)',
                                    '1-3' => 'One third (1/3)',
                                    '2-3' => 'Two thirds (2/3)',
                                    '1-4' => 'One fourth (1/4)',
                                ),
                                'default_value' => '1-1',
                                'allow_null' => 0,
                                'multiple' => 0,
                            ),
                        ),
                    ),
                    array (
                        'label' => 'Images Slider',
                        'name' => 'images_slider',
                        'display' => 'row',
                        'min' => '',
                        'max' => '',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_54cfacf090383',
                                'label' => 'Images',
                                'name' => 'images',
                                'type' => 'gallery',
                                'instructions' => 'Select images to include in the slider',
                                'column_width' => '',
                                'preview_size' => 'thumbnail',
                                'library' => 'all',
                            ),
                            array (
                                'key' => 'field_54cfad5ffe36e',
                                'label' => 'Auto Switch',
                                'name' => 'auto_switch',
                                'type' => 'number',
                                'instructions' => 'Set the number of seconds to auto rotate the images',
                                'column_width' => '',
                                'default_value' => '',
                                'placeholder' => '0 - By default its disabled',
                                'prepend' => '',
                                'append' => '',
                                'min' => 0,
                                'max' => '',
                                'step' => 1,
                            ),
                            array (
                                'key' => 'field_54cfaccc90382',
                                'label' => 'Column Width',
                                'name' => 'column_width',
                                'type' => 'select',
                                'instructions' => 'Columns for image relative to container',
                                'column_width' => '',
                                'choices' => array (
                                    '1-1' => 'Full width (1/1)',
                                    '1-2' => 'Half width (1/2)',
                                    '1-3' => 'One third (1/3)',
                                    '2-3' => 'Two thirds (2/3)',
                                    '1-4' => 'One fourth (1/4)',
                                ),
                                'default_value' => '1-1',
                                'allow_null' => 0,
                                'multiple' => 0,
                            ),
                        ),
                    ),
                    array (
                        'label' => 'YouTube Video',
                        'name' => 'youtube_video',
                        'display' => 'row',
                        'min' => '',
                        'max' => '',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_54ccacb63b7a2',
                                'label' => 'Video URL',
                                'name' => 'video_url',
                                'type' => 'text',
                                'instructions' => 'Enter YouTube video URL',
                                'column_width' => '',
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'formatting' => 'html',
                                'maxlength' => '',
                            ),
                            array (
                                'key' => 'field_54ccace109b54',
                                'label' => 'Video Resolution',
                                'name' => 'video_resolution',
                                'type' => 'text',
                                'instructions' => 'Default is used 16:9',
                                'column_width' => '',
                                'default_value' => '',
                                'placeholder' => '16:9 - Enter in this format {number}:{number}',
                                'prepend' => '',
                                'append' => '',
                                'formatting' => 'html',
                                'maxlength' => '',
                            ),
                            array (
                                'key' => 'field_54ccae1f11501',
                                'label' => 'Video Poster',
                                'name' => 'video_poster',
                                'type' => 'image',
                                'instructions' => 'You can assign video thumbnail (optional)',
                                'conditional_logic' => array (
                                    'status' => 1,
                                    'rules' => array (
                                        array (
                                            'field' => 'field_54ccad7e09b55',
                                            'operator' => '!=',
                                            'value' => 'default',
                                        ),
                                    ),
                                    'allorany' => 'all',
                                ),
                                'column_width' => '',
                                'save_format' => 'object',
                                'preview_size' => 'thumbnail',
                                'library' => 'all',
                            ),
                            array (
                                'key' => 'field_5653182ac91f2',
                                'label' => 'Auto Play',
                                'name' => 'auto_play',
                                'type' => 'true_false',
                                'instructions' => 'Start playing video when page loads',
                                'column_width' => '',
                                'message' => '',
                                'default_value' => 0,
                            ),
                            array (
                                'key' => 'field_565319185d634',
                                'label' => 'Loop',
                                'name' => 'loop',
                                'type' => 'true_false',
                                'instructions' => 'Restart when video ends',
                                'column_width' => '',
                                'message' => '',
                                'default_value' => 0,
                            ),
                            array (
                                'key' => 'field_5653118216551',
                                'label' => 'Default YouTube Player',
                                'name' => 'default_youtube_player',
                                'type' => 'true_false',
                                'instructions' => 'Use YouTube default video player',
                                'column_width' => '',
                                'message' => '',
                                'default_value' => 0,
                            ),
                            array (
                                'key' => 'field_54ccac8c3b7a1',
                                'label' => 'Column Width',
                                'name' => 'column_width',
                                'type' => 'select',
                                'instructions' => 'Columns for image relative to container',
                                'column_width' => '',
                                'choices' => array (
                                    '1-1' => 'Full width (1/1)',
                                    '1-2' => 'Half width (1/2)',
                                    '1-3' => 'One third (1/3)',
                                    '2-3' => 'Two thirds (2/3)',
                                    '1-4' => 'One fourth (1/4)',
                                ),
                                'default_value' => '1-1',
                                'allow_null' => 0,
                                'multiple' => 0,
                            ),
                        ),
                    ),
                    array (
                        'label' => 'Vimeo Video',
                        'name' => 'vimeo_video',
                        'display' => 'row',
                        'min' => '',
                        'max' => '',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_54ccbeeff2d34',
                                'label' => 'Video URL',
                                'name' => 'video_url',
                                'type' => 'text',
                                'instructions' => 'Enter Vimeo video URL',
                                'column_width' => '',
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'formatting' => 'html',
                                'maxlength' => '',
                            ),
                            array (
                                'key' => 'field_54ccbeeff2d35',
                                'label' => 'Video Resolution',
                                'name' => 'video_resolution',
                                'type' => 'text',
                                'instructions' => 'Default is used 16:9',
                                'column_width' => '',
                                'default_value' => '',
                                'placeholder' => '16:9 - Enter in this format {number}:{number}',
                                'prepend' => '',
                                'append' => '',
                                'formatting' => 'html',
                                'maxlength' => '',
                            ),
                            array (
                                'key' => 'field_54ccbeeff2d38',
                                'label' => 'Column Width',
                                'name' => 'column_width',
                                'type' => 'select',
                                'instructions' => 'Columns for image relative to container',
                                'column_width' => '',
                                'choices' => array (
                                    '1-1' => 'Full width (1/1)',
                                    '1-2' => 'Half width (1/2)',
                                    '1-3' => 'One third (1/3)',
                                    '2-3' => 'Two thirds (2/3)',
                                    '1-4' => 'One fourth (1/4)',
                                ),
                                'default_value' => '1-1',
                                'allow_null' => 0,
                                'multiple' => 0,
                            ),
                        ),
                    ),
                    array (
                        'label' => 'Text Quote',
                        'name' => 'text_quote',
                        'display' => 'row',
                        'min' => '',
                        'max' => '',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_54cfa12b726b2',
                                'label' => 'Quote Text',
                                'name' => 'quote_text',
                                'type' => 'textarea',
                                'instructions' => 'Enter the quote text to display in portfolio gallery',
                                'column_width' => '',
                                'default_value' => '',
                                'placeholder' => '',
                                'maxlength' => '',
                                'rows' => 5,
                                'formatting' => 'br',
                            ),
                            array (
                                'key' => 'field_54cfa18bdb105',
                                'label' => 'Quote Author',
                                'name' => 'quote_author',
                                'type' => 'text',
                                'instructions' => 'You may or may not include author name for this quote',
                                'column_width' => '',
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'formatting' => 'html',
                                'maxlength' => '',
                            ),
                            array (
                                'key' => 'field_54cfa10e726b1',
                                'label' => 'Column Width',
                                'name' => 'column_width',
                                'type' => 'select',
                                'instructions' => 'Columns for image relative to container',
                                'column_width' => '',
                                'choices' => array (
                                    '1-1' => 'Full width (1/1)',
                                    '1-2' => 'Half width (1/2)',
                                    '1-3' => 'One third (1/3)',
                                    '2-3' => 'Two thirds (2/3)',
                                    '1-4' => 'One fourth (1/4)',
                                ),
                                'default_value' => '1-1',
                                'allow_null' => 0,
                                'multiple' => 0,
                            ),
                        ),
                    ),
                    array (
                        'label' => 'HTML',
                        'name' => 'html',
                        'display' => 'row',
                        'min' => '',
                        'max' => '',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_565f2603583c9',
                                'label' => 'Content',
                                'name' => 'content',
                                'type' => 'wysiwyg',
                                'instructions' => 'You can also use shortcodes in this field',
                                'column_width' => '',
                                'default_value' => '',
                                'toolbar' => 'full',
                                'media_upload' => 'yes',
                            ),
                            array (
                                'key' => 'field_565f2691583cb',
                                'label' => 'Column Width',
                                'name' => 'column_width',
                                'type' => 'select',
                                'instructions' => 'Columns for image relative to container',
                                'column_width' => '',
                                'choices' => array (
                                    '1-1' => 'Full width (1/1)',
                                    '1-2' => 'Half width (1/2)',
                                    '1-3' => 'One third (1/3)',
                                    '2-3' => 'Two thirds (2/3)',
                                    '1-4' => 'One fourth (1/4)',
                                ),
                                'default_value' => '1-1',
                                'allow_null' => 0,
                                'multiple' => 0,
                            ),
                        ),
                    ),
                ),
                'button_label' => esc_html__( 'Add New', 'onliestwp' ),
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_364fe40alr234',
                            'operator' => '!=',
                            'value' => 'single-3',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'min' => '',
                'max' => '',
            ),
            array(
                'key' => 'field_54d35e2665d2d',
                'label' => esc_html__( 'Gallery', 'onliestwp' ),
                'name' => 'gallery',
                'type' => 'flexible_content',
                'instructions' => esc_html__( 'Select all images you want to show for this portfolio item.', 'onliestwp' ),
                'layouts' => array(
                    array(
                        'label' => esc_html__( 'Image', 'onliestwp' ),
                        'name' => 'image',
                        'display' => 'row',
                        'min' => '',
                        'max' => '',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_54cb900997f72',
                                'label' => esc_html__( 'Image', 'onliestwp' ),
                                'name' => 'image',
                                'type' => 'image',
                                'instructions' => esc_html__( 'Image that will be shown', 'onliestwp' ),
                                'column_width' => 60,
                                'save_format' => 'object',
                                'preview_size' => 'thumbnail',
                                'library' => 'all',
                            ),
                            array (
                                'key' => 'field_54d221bb45227',
                                'label' => esc_html__( 'Link URL', 'onliestwp' ),
                                'name' => 'link_url',
                                'type' => 'text',
                                'instructions' => esc_html__( 'You may include custom link for this slide (optional)', 'onliestwp' ),
                                'column_width' => '',
                                'default_value' => '',
                                'placeholder' => 'http://',
                                'prepend' => '',
                                'append' => '',
                                'formatting' => 'html',
                                'maxlength' => '',
                            ),
                            array (
                                'key' => 'field_54d221f745228',
                                'label' => esc_html__( 'Link Target', 'onliestwp' ),
                                'name' => 'link_target',
                                'type' => 'true_false',
                                'instructions' => esc_html__( 'Set the link target when user clicks on it', 'onliestwp' ),
                                'column_width' => '',
                                'message' => 'Open in new window',
                                'default_value' => 1,
                            ),
                        ),
                    ),
                ),
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_364fe40alr234',
                            'operator' => '==',
                            'value' => 'single-3',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'button_label' => esc_html__( 'Add New', 'onliestwp' ),
                'min' => '',
                'max' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'portfolio',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array(
            'position' => 'normal',
            'layout' => 'default',
            'hide_on_screen' => array(),
        ),
        'menu_order' => 20,
    ) );

}